using System.Globalization;

namespace Vacate.App.Localization;

/// <summary>
/// Тексты интерфейса на двух языках.
/// </summary>
/// <remarks>
/// Словарь в коде, а не файлы ресурсов. Причина не в лени: тексты этого продукта
/// объясняют, что произойдёт с чужими файлами, и они переписываются вместе с кодом,
/// который эти действия выполняет. Разложенные по отдельным файлам, они расходятся
/// с поведением незаметно — переводчик правит одно, разработчик другое.
///
/// Русский — основной. Если ключа нет в английском словаре, возвращается русский текст:
/// показать ключ вместо фразы значит показать человеку внутренности программы.
/// </remarks>
public static class Strings
{
    private static readonly Dictionary<string, string> Russian = new(StringComparer.Ordinal)
    {
        // Общее
        ["App.Name"] = "Vacate",
        ["Common.Refresh"] = "Обновить",
        ["Common.Cancel"] = "Отмена",
        ["Common.Close"] = "Закрыть",
        ["Common.Continue"] = "Продолжить?",
        ["Common.Reading"] = "Читаю…",
        ["Common.Version"] = "версия",
        ["Common.NeedsRights"] = "нужны права",
        ["Common.NoRightsHere"] = "Часть данных недоступна без прав администратора.",

        // Разделы
        ["Nav.Dashboard"] = "Обзор",
        ["Nav.Clean"] = "Очистка мусора",
        ["Nav.Apps"] = "Программы",
        ["Nav.Startup"] = "Автозагрузка",
        ["Nav.Extensions"] = "Расширения браузеров",
        ["Nav.Disk"] = "Место на диске",
        ["Nav.Health"] = "Состояние системы",
        ["Nav.Settings"] = "Настройки",

        // Очистка
        ["Clean.Title"] = "Очистка мусора",
        ["Clean.Subtitle"] = "Снимите отметку с того, что трогать не нужно. Файлы моложе суток не удаляются в любом случае: их может использовать работающая программа.",
        ["Clean.Scan"] = "Сканировать",
        ["Clean.Preview"] = "Показать, что будет сделано",
        ["Clean.Run"] = "Очистить",
        ["Clean.Scanning"] = "Сканирую…",
        ["Clean.Working"] = "Очищаю…",
        ["Clean.DryRunning"] = "Пробный прогон…",
        ["Clean.Result"] = "Результат",
        ["Clean.Empty"] = "Чисто. Мусор накапливается примерно за неделю.",
        ["Clean.NothingChecked"] = "Не отмечено ни одной категории.",

        // Программы
        ["Apps.Title"] = "Программы",
        ["Apps.Subtitle"] = "Выберите программу и нажмите «Удалить». Несколько сразу — с зажатой клавишей Ctrl: тогда они удалятся одна за другой.",
        ["Apps.Uninstall"] = "Удалить программу",
        ["Apps.Hunt"] = "Найти по окну",
        ["Apps.Runtime"] = "нужна другим",
        ["Apps.UserOnly"] = "только для вас",
        ["Apps.UnknownSize"] = "размер неизвестен",

        // Автозагрузка
        ["Startup.Title"] = "Автозагрузка",
        ["Startup.Subtitle"] = "Выберите запись и нажмите кнопку, чтобы включить или отключить её. Критичные системные службы показаны, но переключить их нельзя.",
        ["Startup.Toggle"] = "Включить или отключить",
        ["Startup.Enabled"] = "включено",
        ["Startup.Disabled"] = "выключено",
        ["Startup.ViewOnly"] = "только просмотр",

        // Расширения
        ["Extensions.Title"] = "Расширения браузеров",
        ["Extensions.Subtitle"] = "Главное здесь — какие права расширение себе выпросило. Отключение делается в самом браузере: правку его настроек извне он отменяет при запуске.",
        ["Extensions.ReadsAllSites"] = "читает все сайты",

        // Диск
        ["Disk.Title"] = "Место на диске",
        ["Disk.Subtitle"] = "Куда уходит место в вашей личной папке. Выберите крупный файл или группу копий и нажмите «Удалить» — всё уйдёт в Корзину.",
        ["Disk.Delete"] = "Удалить выбранное",
        ["Disk.ShowMap"] = "Показать картой",
        ["Disk.LargeFile"] = "крупный файл",
        ["Disk.Duplicates"] = "дубликаты",
        ["Disk.InCloud"] = "в облачной папке",

        // Состояние
        ["Health.Title"] = "Состояние системы",
        ["Health.Subtitle"] = "Показатели берутся у самих накопителей. Если диск их не сообщает, здесь будет честное «не сообщает», а не выдуманная оценка.",
        ["Health.CheckIntegrity"] = "Проверить целостность системы",

        // Настройки
        ["Settings.Title"] = "Настройки",
        ["Settings.Subtitle"] = "Всё, что программа делает без вашего участия, включается здесь — и здесь же выключается.",
        ["Settings.Schedule"] = "Автоматическая очистка",
        ["Settings.ScheduleOff"] = "Выключена",
        ["Settings.ScheduleWeekly"] = "Раз в неделю",
        ["Settings.ScheduleMonthly"] = "Раз в месяц",
        ["Settings.AtLogon"] = "Ещё и при входе в систему",
        ["Settings.Apply"] = "Применить",
        ["Settings.Tray"] = "Область уведомлений",
        ["Settings.ShowTray"] = "Показывать значок рядом с часами",
        ["Settings.MinimizeToTray"] = "Кнопка «закрыть» прячет программу, а не выходит из неё",
        ["Settings.Updates"] = "Обновления",
        ["Settings.CheckUpdates"] = "Проверять наличие новой версии",
        ["Settings.Rollback"] = "Где лежит то, что можно вернуть",
        ["Settings.OpenQuarantine"] = "Открыть карантин",
        ["Settings.OpenBackups"] = "Открыть копии реестра",
        ["Settings.CreateRestorePoint"] = "Создать точку восстановления",
        ["Settings.ShowTour"] = "Показать знакомство",
        ["Settings.Language"] = "Язык",
        ["Settings.LanguageNote"] = "Смена языка применяется при следующем запуске программы.",
        ["Settings.LanguageRussian"] = "Русский",
        ["Settings.LanguageEnglish"] = "English",

        // Пояснения в настройках
        ["Settings.ScheduleNote"] = "Задача в планировщике Windows. Выполняются только безопасные категории: временные файлы и кэши. Реестр и программы автоматика не трогает никогда — действие без человека за экраном не должно быть необратимым.",
        ["Settings.TrayNote"] = "Значок рядом с часами. Из его меню запускается быстрая очистка — без открытия окна и без вопросов.",
        ["Settings.UpdatesNote"] = "Единственное обращение программы в сеть: раз в сутки она спрашивает страницу проекта, нет ли версии новее. Ничего не скачивается и не устанавливается само.",
        ["Settings.RollbackNote"] = "Удалённые каталоги хранятся 30 дней, копии ветвей реестра — до тех пор, пока вы их не удалите сами.",
        ["Settings.ScheduleOffNow"] = "Сейчас выключена.",
        ["Settings.ScheduleOnNow"] = "Включена.",
        ["Settings.NextRun"] = "Следующий запуск:",
        ["Settings.NoCli"] = "Рядом с программой нет vacate-cli.exe — поставка неполная.",
        ["Settings.QuarantineEmpty"] = "Карантин пуст: возвращать нечего.",
        ["Settings.NoBackups"] = "Копий ветвей реестра ещё не создавалось.",
        ["Settings.UpdatesOffTitle"] = "Обновления отключены",
        ["Settings.UpdatesOffBody"] = "Программа больше не будет обращаться в сеть.\n\nПроверить наличие новой версии можно вручную на странице проекта:\ngithub.com/Egor062020/Vacate/releases",

        // Знакомство
        ["Tour.Title"] = "С чего начать",
        ["Tour.Skip"] = "Пропустить",
        ["Tour.Next"] = "Дальше",
        ["Tour.Done"] = "Понятно",
        ["Tour.StepOf"] = "{0} из {1}",

        ["Tour.1.Title"] = "Ничего не исчезнет само",
        ["Tour.1.Body"] = "Vacate сначала показывает, что нашла, и ждёт вашего решения. Ни одна кнопка не удаляет файлы сразу: сперва список, потом подтверждение, и только потом работа.\n\nВ разделе «Очистка мусора» есть кнопка «Показать, что будет сделано». Она проходит весь путь до конца, но не меняет на диске ни байта.",
        ["Tour.1.Aside"] = "Начните с неё, если сомневаетесь. Пробный прогон ничего не ломает — это его назначение.",

        ["Tour.2.Title"] = "Удалённое можно вернуть",
        ["Tour.2.Body"] = "Папки удалённых программ не стираются, а перекладываются в служебное хранилище и лежат там 30 дней. Ваши файлы — крупные и одинаковые копии — уходят в Корзину, откуда вы вернёте их привычным способом.\n\nВетви реестра сохраняются в файл перед удалением: он открывается двойным щелчком и возвращает всё на место.",
        ["Tour.2.Aside"] = "Временные файлы и кэши — исключение: они удаляются насовсем. Они создаются заново, и хранить их копии значило бы не освободить ни мегабайта.",

        ["Tour.3.Title"] = "Цифры честные",
        ["Tour.3.Body"] = "После работы показываются две величины: сколько удалено и сколько на самом деле освободилось. Они часто различаются — файл держит работающая программа, или удалённое ждёт в Корзине.\n\nРазница объясняется построчно, а не прячется.",
        ["Tour.3.Aside"] = "Если очистка не дала результата, программа скажет об этом прямо, а не припишет себе чужие гигабайты.",

        ["Tour.4.Title"] = "Куда нажимать",
        ["Tour.4.Body"] = "Слева разделы. «Очистка мусора» — временные файлы, самое безопасное. «Программы» — удаление вместе со следами, которые деинсталлятор оставил после себя. «Автозагрузка» — то, что стартует вместе с Windows.\n\n«Место на диске» покажет, куда оно ушло, а кнопка «Показать картой» — как это соотносится между собой. В «Настройках» включается автоматическая очистка и значок рядом с часами.",
        ["Tour.4.Aside"] = "Красным помечено то, что требует внимания. Серым — то, что программа трогать не станет.",

        // Обновления
        ["Update.Available"] = "Вышла версия {0}. Установка не начнётся сама: пока у программы нет подписи кода, запускать обновление без вашего ведома нельзя.",
        ["Update.Open"] = "Открыть страницу",
        ["Update.Later"] = "Не сейчас",
        ["Update.Never"] = "Не проверять больше",

        // Удаление программы
        ["Uninstall.WindowTitle"] = "Удаление программы",
        ["Uninstall.ConfirmSubtitle"] = "Проверьте, что это именно та программа. После запуска остановить деинсталлятор нельзя.",
        ["Uninstall.Publisher"] = "Издатель:",
        ["Uninstall.Version"] = "Версия:",
        ["Uninstall.Location"] = "Каталог:",
        ["Uninstall.Scope"] = "Установка:",
        ["Uninstall.NotSpecified"] = "не указан",
        ["Uninstall.VersionUnknown"] = "не указана",
        ["Uninstall.ForAll"] = "для всех пользователей",
        ["Uninstall.ForYou"] = "только для вас",
        ["Uninstall.WarningTitle"] = "Стоит знать до нажатия",
        ["Uninstall.HowTitle"] = "Как это будет",
        ["Uninstall.How1"] = "1. Запустится деинсталлятор самой программы. Он чужой: что он спросит и что удалит, решает он, а не Vacate.",
        ["Uninstall.How2"] = "2. Затем Vacate поищет то, что деинсталлятор оставил после себя.",
        ["Uninstall.How3"] = "3. Найденное покажет списком — удалять или нет, решите вы. Ничего не исчезнет без вашей отметки.",
        ["Uninstall.Start"] = "Удалить программу",
        ["Uninstall.StartForced"] = "Удалить принудительно",
        ["Uninstall.RemoveMarked"] = "Удалить отмеченное",
        ["Uninstall.LeaveAsIs"] = "Оставить как есть",
        ["Uninstall.RunningTitle"] = "Работает деинсталлятор",
        ["Uninstall.RunningSubtitle"] = "Отвечайте на его вопросы в его собственном окне. Vacate ждёт, пока он закончит.",
        ["Uninstall.Running"] = "Идёт удаление «{0}»…",
        ["Uninstall.SearchingTitle"] = "Ищу следы",
        ["Uninstall.SearchingSubtitle"] = "Смотрю каталоги программ и ветки реестра.",
        ["Uninstall.Searching"] = "Поиск следов…",
        ["Uninstall.LeftoversTitle"] = "Что осталось после деинсталлятора",
        ["Uninstall.LeftoversSubtitle"] = "Снимите отметку со всего, в чём не уверены. Удалено будет только отмеченное.",
        ["Uninstall.RemovingTitle"] = "Убираю следы",
        ["Uninstall.RemovingSubtitle"] = "Каталоги перемещаются в карантин, ветки реестра удаляются.",
        ["Uninstall.RemovingElevated"] = "Часть следов лежит в системных папках: Windows сейчас спросит права администратора.",
        ["Uninstall.Removing"] = "Удаление: {0} объектов…",
        ["Uninstall.Done"] = "Готово",
        ["Uninstall.NothingRemoved"] = "Ничего не удалено",
        ["Uninstall.WhatHappened"] = "Что произошло:",
        ["Uninstall.NoTraces"] = "Файлов программы не найдено.",
        ["Uninstall.FailedTitle"] = "Удаление не завершилось",
        ["Uninstall.FailedBody"] = "Деинсталлятор не отработал.",
        ["Uninstall.FailedNote"] = "Следы не искали: программа, возможно, осталась на месте, и её рабочие файлы можно было бы принять за остатки.",
        ["Uninstall.WorkedOut"] = "Деинсталлятор отработал.",
        ["Uninstall.NothingChecked"] = "Не отмечено ни одного объекта. Программа удалена, следы остались на месте.",
        ["Uninstall.NothingLeft"] = "Удалять нечего",
        ["Uninstall.VanishedWhileReading"] = "Отмеченные объекты исчезли, пока вы читали список.",
        ["Uninstall.WarnRuntime"] = "Похоже на компонент, нужный другим программам. После удаления те из них, что на него опираются, перестанут запускаться — и связь с этим действием будет уже не очевидна.",
        ["Uninstall.WarnNoUninstaller"] = "Программа не сообщила системе, как её удалять. Vacate поищет оставшиеся файлы и уберёт запись из списка установленного.",
        ["Uninstall.WarnMissingUninstaller"] = "Деинсталлятор программы не найден: запись пережила саму программу. Vacate поищет оставшиеся файлы и уберёт запись из списка установленного.",
        ["Uninstall.WarnMachineScope"] = "Программа установлена для всех пользователей: Windows запросит права администратора.",
        ["Uninstall.HintUnchecked"] = "Отмечено {0} из {1}. Не отмечены совпадения уровня «возможно»: за ними стоит только часть имени, и это может оказаться чужой каталог. Проверьте пути глазами.",
        ["Uninstall.HintAll"] = "Отмечено всё найденное: {0}. Каталоги уйдут в карантин и вернутся кнопкой отката.",
        ["Uninstall.Certain"] = "точно её",
        ["Uninstall.Likely"] = "скорее всего её",
        ["Uninstall.Possible"] = "возможно, чужое",
        ["Uninstall.Directory"] = "Каталог",
        ["Uninstall.RegistryKey"] = "Ветка реестра",
        ["Uninstall.RemovedCount"] = "Удалено объектов: {0}",
        ["Uninstall.FreedOf"] = "Реально освободилось: {0} из заявленных {1}",
        ["Uninstall.ByElevated"] = "Выполнено отдельным процессом с правами администратора.",
        ["Uninstall.Skipped"] = "Пропущено: {0}",
        ["Uninstall.Failed"] = "Не удалось удалить: {0}",
        ["Uninstall.Denied"] = "Отклонено проверками безопасности: {0}",
        ["Uninstall.UndoHint"] = "Каталоги лежат в карантине 30 дней. Вернуть их можно командой:",
        ["Uninstall.BackupHint"] = "Копия удалённых ветвей реестра сохранена:",
        ["Uninstall.BackupHowTo"] = "Чтобы вернуть их, откройте этот файл двойным щелчком.",
        ["Uninstall.RightsRefused"] = "Следы остались на месте. Программа при этом уже удалена.",
        ["Uninstall.StillListed"] = "Программа останется в списке установленного. Попробуйте ещё раз или уберите запись через «Параметры → Приложения».",
        ["Apps.NoUninstallCommand"] = "Программа не сообщила системе, как её удалять",
        ["Apps.Status"] = "Всего {0}, из них сред выполнения {1}. Размер указан самой программой и часто занижен.",
        ["Apps.BatchTitle"] = "Удаление нескольких программ",
        ["Apps.BatchBody"] = "Выбрано программ: {0}.\n\n{1}\n\nОни будут удалены по очереди: для каждой откроется своё окно, и каждый деинсталлятор задаст свои вопросы.\n\nПрервать можно в любой момент — отменённые останутся на месте.\n\nПродолжить?",
        ["Startup.CannotToggle"] = "Эту запись переключать нельзя: без неё система может перестать работать.",
        ["Startup.TurnOn"] = "включить",
        ["Startup.TurnOff"] = "отключить",
        ["Startup.ConfirmTitle"] = "Автозагрузка: {0}",
        ["Startup.WillBeOn"] = "Автозапуск «{0}» будет включён.\n\n",
        ["Startup.WillBeOff"] = "Автозапуск «{0}» будет отключён.\n\n",
        ["Startup.ServiceNote"] = "Служба перейдёт в режим «вручную»: сама при загрузке не стартует, но программа, которой она нужна, поднимет её по требованию.\n\n",
        ["Startup.ShortcutNote"] = "Ярлык будет переименован, а не удалён — вернуть можно тем же движением.\n\n",
        ["Startup.RegistryNote"] = "Запись не удаляется, а помечается — тем же способом, которым это делает диспетчер задач. Вернуть можно в любой момент.\n\n",
        ["Startup.ElevationNote"] = "Запись общая для всех пользователей, поэтому Windows запросит права администратора.\n\n",
        ["Startup.NoExecutor"] = "Не удалось запустить исполнителя.",
        ["Startup.ToggleFailed"] = "Переключить запись не удалось. Подробности — в команде: vacate-cli startup",
        ["Startup.RightsRefused"] = "Вы отказались предоставить права администратора.",
        ["Startup.Status"] = "Программ {0}, служб {1}.",
        ["Startup.SourceRegistry"] = "реестр",
        ["Startup.SourceFolder"] = "папка автозагрузки",
        ["Startup.SourceTask"] = "задача",
        ["Startup.SourceService"] = "служба",
        ["Extensions.StatusDangerous"] = "Всего {0}. С доступом ко всем сайтам: {1} — такое расширение видит всё, что вы открываете.",
        ["Extensions.StatusSafe"] = "Всего {0}. Расширений с доступом ко всем сайтам нет.",
        ["Disk.DeleteTitle"] = "Удаление файлов",
        ["Disk.NotAFile"] = "Эта строка — сводка по виду файлов, а не отдельный файл.\n\nВыберите крупный файл или группу одинаковых копий.",
        ["Disk.ListStale"] = "Файлы уже исчезли — список устарел. Обновите его.",
        ["Disk.OneFile"] = "Файл «{0}» ({1})",
        ["Disk.ExtraCopies"] = "Лишние копии: {0} шт., освободится {1}",
        ["Disk.WillKeep"] = "Останется: {0}\n\n",
        ["Disk.CloudWarning"] = "ВНИМАНИЕ: файл лежит в синхронизируемой папке. Он исчезнет на всех ваших устройствах, включая телефон, а Корзина вернёт его только здесь.\n\n",
        ["Disk.ToRecycleBin"] = "Всё удалённое уходит в Корзину.\n\nПродолжить?",
        ["Disk.DeleteResult"] = "Удалено: {0}. Освободилось: {1}.\n\nМесто вернётся полностью после очистки Корзины.",
        ["Disk.FileKind"] = "вид файлов",
        ["Disk.FilesCount"] = "{0} файлов",
        ["Disk.CloudNote"] = "Удаление уйдёт на все ваши устройства",
        ["Disk.CopiesCount"] = "{0} одинаковых копии",
        ["Disk.CopiesNote"] = "Освободится столько, если оставить одну копию",
        ["Disk.CopiesCloudNote"] = "Освободится столько, если оставить одну копию. Удаление уйдёт на все ваши устройства",
        ["Disk.Status"] = "Просмотрено {0} файлов, {1}.",
        ["Disk.StatusDuplicates"] = " На копиях можно вернуть {0}.",
        ["Disk.StatusSkipped"] = " Не вошло в подсчёт: {0}.",
        ["Integrity.Title"] = "Проверка целостности",
        ["Integrity.Confirm"] = "Windows проверит свои системные файлы и восстановит повреждённые.\n\nЭто занимает от 10 до 40 минут. Остановить проверку нельзя: закрытие её окна работу не прервёт.\n\nОткроется окно с ходом проверки, и Windows запросит права администратора.\n\nЗапустить?",
        ["Integrity.NoCli"] = "Рядом с программой нет файла vacate-cli.exe, который выполняет проверку.\n\nПохоже, поставка неполная — переустановите программу.",
        ["Integrity.NoResult"] = "Проверка завершилась, но итог прочитать не удалось.",
        ["Integrity.NoReport"] = "Проверка завершилась, но итог не дошёл до программы.",
        ["Health.Temperature"] = "температура {0} °C",
        ["Health.Wear"] = "износ {0}%",
        ["Health.PowerOn"] = "наработка {0} ч",
        ["Health.NotReported"] = "Диск не сообщает: {0}",
        ["Health.NeedsAttention"] = "требует внимания",
        ["Health.Healthy"] = "исправен",
        ["Health.Warning"] = "предупреждения",
        ["Health.Unhealthy"] = "неисправен",
        ["Health.Unknown"] = "не сообщил",
        ["Health.NoDisks"] = "Сведения о дисках недоступны. Часть данных требует прав администратора.",
        ["Health.DiskCount"] = "Дисков: {0}.",
        ["Clean.Found"] = "Найдено {0} объектов, {1}. Это оценка сверху: часть файлов может быть занята.",
        ["Clean.CatBrowsers"] = "Сайты откроются в первый раз заметно медленнее. Пароли и вкладки не тронутся.",
        ["Clean.CatLogs"] = "Журналы событий системы. Нужны только при разборе неполадок.",
        ["Clean.CatCrash"] = "Отчёты об уже случившихся сбоях программ.",
        ["Clean.CatDelivery"] = "Загруженные обновления Windows. При необходимости скачаются заново.",
        ["Clean.NeedsRightsNote"] = "Окно программы работает без прав администратора и не может сюда заглянуть. Отметьте — и при очистке Windows запросит права, а работу выполнит отдельный процесс.",
        ["Clean.AndMore"] = "{0}  и ещё {1}",
        ["Clean.ConfirmTitle"] = "Очистка",
        ["Clean.NothingCheckedBody"] = "Не отмечено ни одной категории. Отметьте хотя бы одну — иначе удалять нечего.",
        ["Clean.ConfirmBody"] = "Будет удалено {0} объектов, около {1}.\n\nЭто временные файлы и кэши: они создаются заново, но восстановить их будет нельзя.",
        ["Clean.ConfirmElevatedOnly"] = "Отмечены категории, которые окно программы прочитать не может.\n\nИх просканирует и очистит отдельный процесс с правами администратора.",
        ["Clean.WhatWillGo"] = "\n\nЧто будет очищено:\n",
        ["Clean.ElevationNote"] = "\n\nЧасть файлов лежит в системных папках, поэтому Windows спросит права администратора. Само окно программы этих прав не получает: работу выполнит отдельный процесс.",
        ["Clean.WouldProcess"] = "Было бы обработано: {0} объектов, {1}.",
        ["Clean.NothingChangedOnDisk"] = "На диске ничего не изменилось.",
        ["Clean.Deleted"] = "Удалено: {0} объектов, заявлено {1}.",
        ["Clean.ByElevated"] = " Выполнено процессом с правами администратора.",
        ["Clean.ActuallyFreed"] = "Реально освободилось: {0}",
        ["Clean.WhyHeld"] = "занято работающей программой, вернётся при её закрытии",
        ["Clean.WhyNotDeleted"] = "не удалось удалить",
        ["Clean.WhyHardLinked"] = "файл числится дважды, а занимает место один раз",
        ["Clean.WhyCompressed"] = "сжатые файлы занимали на диске меньше",
        ["Clean.WhyQuarantine"] = "в карантине, освободится после истечения срока",
        ["Clean.WhyRecycleBin"] = "в Корзине, освободится после её очистки",
        ["Clean.Cat.TempUser"] = "Временные файлы пользователя",
        ["Clean.Cat.TempSystem"] = "Временные файлы системы",
        ["Clean.Cat.Logs"] = "Журналы Windows",
        ["Clean.Cat.Browsers"] = "Кэши браузеров",
        ["Clean.Cat.Crash"] = "Отчёты о сбоях программ",
        ["Clean.Cat.Delivery"] = "Загруженные обновления Windows",
        ["Clean.Cat.Other"] = "Прочее",
        ["Dashboard.Title"] = "Обзор",
        ["Dashboard.Subtitle"] = "Что происходит с этим компьютером прямо сейчас.",
        ["Dashboard.Scan"] = "Посмотреть, что найдётся",
        ["Map.Title"] = "Карта диска",
        ["Map.Subtitle"] = "Площадь прямоугольника — занятое место. Щелчок открывает папку, двойной щелчок по «файлам в этой папке» показывает её в проводнике.",
        ["Map.Up"] = "Наверх",
        ["Map.Counting"] = "Считаю размеры…",
        ["Map.Empty"] = "Здесь пусто или содержимое недоступно.",
        ["Map.Total"] = "Всего {0} в {1} объектах.",
        ["Map.Unreadable"] = " Не удалось прочитать: {0} — их место в подсчёт не вошло.",
        ["Map.TooSmall"] = " Слишком мелкие, чтобы показать их на карте: {0}.",
        ["Map.LooseFiles"] = "файлы в этой папке",
        ["Hunter.Title"] = "Что это за программа",
        ["Hunter.Subtitle"] = "Нажмите на прицел, не отпуская кнопку, доведите его до нужного окна и отпустите. Vacate определит, чем это окно запущено.",
        ["Hunter.Uninstall"] = "Удалить эту программу",
        ["Hunter.PointAt"] = "Наведите прицел на окно",
        ["Hunter.Dragging"] = "Ведите прицел к нужному окну…",
        ["Hunter.NotIdentified"] = "Программа не определена",
        ["Hunter.WindowTitle"] = "Заголовок окна: {0}",
        ["Hunter.StartedFrom"] = "Запущено из:    {0}",
        ["Crash.Title"] = "Vacate",
        ["Crash.Body"] = "Произошла ошибка, которую программа не смогла обработать.\n\nЧто случилось: {0}\n",
        ["Crash.Saved"] = "Подробности сохранены в файл:\n{0}\n\nЕго можно приложить к сообщению об ошибке — личные данные из него убраны.",
        ["Tray.Open"] = "Открыть Vacate",
        ["Tray.QuickClean"] = "Быстрая очистка",
        ["Tray.Exit"] = "Выход",
        ["Tray.Tooltip"] = "Vacate — очистка и обслуживание",
        ["Tray.Started"] = "Очистка запущена в фоне.",
        ["Tray.NoCli"] = "Рядом с программой нет vacate-cli.exe — поставка неполная.",
        ["Elevated.NoReport"] = "Работа выполнена, но подробности от поднятого процесса не дошли",
        ["Common.Items"] = "шт.",
        ["Window.Minimize"] = "Свернуть",
        ["Window.Maximize"] = "Развернуть",
        ["Dashboard.Space"] = "Свободно на системном диске",
        ["Dashboard.Subtitle2"] = "Состояние компьютера и что можно сделать прямо сейчас.",
        ["Dashboard.FreeSpace"] = "СВОБОДНО НА СИСТЕМНОМ ДИСКЕ",
        ["Dashboard.CanFree"] = "МОЖНО ОСВОБОДИТЬ",
        ["Dashboard.StartupCount"] = "ПРОГРАММ В АВТОЗАПУСКЕ",
        ["Dashboard.WhereToStart"] = "С чего начать",
        ["Dashboard.QuickNote"] = "Быстрая очистка убирает только то, что создаётся заново: временные файлы и кэши. Реестр и программы она не трогает.",
        ["Dashboard.LastCleanup"] = "Последняя очистка",
        ["Dashboard.NoCleanups"] = "Очисток пока не было.",
        ["Dashboard.DiskFull"] = "Диск заполнен на {0}%",
        ["Dashboard.DiskFullNote"] = "При нехватке свободного места Windows начинает работать заметно медленнее.",
        ["Dashboard.DiskAttention"] = "Диск {0}: показатели требуют внимания",
        ["Dashboard.DiskAttentionNote"] = "Сделайте резервную копию важных данных.",
        ["Dashboard.ManyStartup"] = "В автозапуске {0} программ",
        ["Dashboard.ManyStartupNote"] = "Каждая из них добавляет секунды ко времени входа в систему.",
        ["Dashboard.LastSession"] = "{0} — обработано {1} объектов, заявлено {2}, реально освободилось {3}.",
        ["Dashboard.Searching"] = "Ищу…",
        ["Dashboard.FoundJunk"] = "Найдено {0} объектов. Подробности — в разделе «Очистка мусора».",
    };

    private static readonly Dictionary<string, string> English = new(StringComparer.Ordinal)
    {
        ["App.Name"] = "Vacate",
        ["Common.Refresh"] = "Refresh",
        ["Common.Cancel"] = "Cancel",
        ["Common.Close"] = "Close",
        ["Common.Continue"] = "Continue?",
        ["Common.Reading"] = "Reading…",
        ["Common.Version"] = "version",
        ["Common.NeedsRights"] = "needs rights",
        ["Common.NoRightsHere"] = "Some of this is unreadable without administrator rights.",

        ["Nav.Dashboard"] = "Overview",
        ["Nav.Clean"] = "Junk cleanup",
        ["Nav.Apps"] = "Programs",
        ["Nav.Startup"] = "Startup",
        ["Nav.Extensions"] = "Browser extensions",
        ["Nav.Disk"] = "Disk space",
        ["Nav.Health"] = "System state",
        ["Nav.Settings"] = "Settings",

        ["Clean.Title"] = "Junk cleanup",
        ["Clean.Subtitle"] = "Uncheck anything you would rather keep. Files younger than a day are never deleted: a running program may still be using them.",
        ["Clean.Scan"] = "Scan",
        ["Clean.Preview"] = "Show what would happen",
        ["Clean.Run"] = "Clean",
        ["Clean.Scanning"] = "Scanning…",
        ["Clean.Working"] = "Cleaning…",
        ["Clean.DryRunning"] = "Dry run…",
        ["Clean.Result"] = "Result",
        ["Clean.Empty"] = "Nothing to clean. Junk builds up over about a week.",
        ["Clean.NothingChecked"] = "No categories are checked.",

        ["Apps.Title"] = "Programs",
        ["Apps.Subtitle"] = "Select a program and press Uninstall. Hold Ctrl to select several — they are removed one after another.",
        ["Apps.Uninstall"] = "Uninstall program",
        ["Apps.Hunt"] = "Find by window",
        ["Apps.Runtime"] = "other programs need it",
        ["Apps.UserOnly"] = "just for you",
        ["Apps.UnknownSize"] = "size unknown",

        ["Startup.Title"] = "Startup",
        ["Startup.Subtitle"] = "Select an entry and press the button to turn it on or off. Critical system services are listed but cannot be switched.",
        ["Startup.Toggle"] = "Turn on or off",
        ["Startup.Enabled"] = "on",
        ["Startup.Disabled"] = "off",
        ["Startup.ViewOnly"] = "view only",

        ["Extensions.Title"] = "Browser extensions",
        ["Extensions.Subtitle"] = "What matters here is the permissions an extension asked for. Turning one off is done in the browser itself: it reverts outside edits on startup.",
        ["Extensions.ReadsAllSites"] = "reads every site",

        ["Disk.Title"] = "Disk space",
        ["Disk.Subtitle"] = "Where the space in your own folder went. Select a large file or a group of copies and press Delete — everything goes to the Recycle Bin.",
        ["Disk.Delete"] = "Delete selected",
        ["Disk.ShowMap"] = "Show as a map",
        ["Disk.LargeFile"] = "large file",
        ["Disk.Duplicates"] = "duplicates",
        ["Disk.InCloud"] = "in a synced folder",

        ["Health.Title"] = "System state",
        ["Health.Subtitle"] = "Readings come from the drives themselves. When a drive does not report them, it says so plainly instead of inventing a score.",
        ["Health.CheckIntegrity"] = "Check system integrity",

        ["Settings.Title"] = "Settings",
        ["Settings.Subtitle"] = "Everything the program does unattended is turned on here — and off here.",
        ["Settings.Schedule"] = "Automatic cleanup",
        ["Settings.ScheduleOff"] = "Off",
        ["Settings.ScheduleWeekly"] = "Weekly",
        ["Settings.ScheduleMonthly"] = "Monthly",
        ["Settings.AtLogon"] = "Also at sign-in",
        ["Settings.Apply"] = "Apply",
        ["Settings.Tray"] = "Notification area",
        ["Settings.ShowTray"] = "Show an icon next to the clock",
        ["Settings.MinimizeToTray"] = "The close button hides the program instead of quitting",
        ["Settings.Updates"] = "Updates",
        ["Settings.CheckUpdates"] = "Check for a newer version",
        ["Settings.Rollback"] = "Where the recoverable things are kept",
        ["Settings.OpenQuarantine"] = "Open quarantine",
        ["Settings.OpenBackups"] = "Open registry backups",
        ["Settings.CreateRestorePoint"] = "Create a restore point",
        ["Settings.ShowTour"] = "Show the walkthrough",
        ["Settings.Language"] = "Language",
        ["Settings.LanguageNote"] = "The language changes the next time the program starts.",
        ["Settings.LanguageRussian"] = "Русский",
        ["Settings.LanguageEnglish"] = "English",

        ["Settings.ScheduleNote"] = "A task in the Windows scheduler. Only safe categories run: temporary files and caches. The registry and installed programs are never touched unattended — an action taken with nobody at the screen must not be irreversible.",
        ["Settings.TrayNote"] = "An icon next to the clock. Its menu starts a quick cleanup — no window, no questions.",
        ["Settings.UpdatesNote"] = "The only time this program touches the network: once a day it asks the project page whether a newer version exists. Nothing is downloaded or installed on its own.",
        ["Settings.RollbackNote"] = "Deleted directories are kept for 30 days; registry backups stay until you remove them yourself.",
        ["Settings.ScheduleOffNow"] = "Currently off.",
        ["Settings.ScheduleOnNow"] = "On.",
        ["Settings.NextRun"] = "Next run:",
        ["Settings.NoCli"] = "vacate-cli.exe is missing next to the program — the installation is incomplete.",
        ["Settings.QuarantineEmpty"] = "Quarantine is empty: there is nothing to restore.",
        ["Settings.NoBackups"] = "No registry backups have been made yet.",
        ["Settings.UpdatesOffTitle"] = "Updates turned off",
        ["Settings.UpdatesOffBody"] = "The program will no longer reach the network.\n\nYou can check for a newer version yourself on the project page:\ngithub.com/Egor062020/Vacate/releases",

        ["Tour.Title"] = "Where to start",
        ["Tour.Skip"] = "Skip",
        ["Tour.Next"] = "Next",
        ["Tour.Done"] = "Got it",
        ["Tour.StepOf"] = "{0} of {1}",

        ["Tour.1.Title"] = "Nothing disappears on its own",
        ["Tour.1.Body"] = "Vacate shows what it found and waits for your decision. No button deletes anything straight away: first the list, then the confirmation, and only then the work.\n\nJunk cleanup has a button called “Show what would happen”. It walks the whole path to the end without changing a single byte on disk.",
        ["Tour.1.Aside"] = "Start there if you are unsure. A dry run cannot break anything — that is what it is for.",

        ["Tour.2.Title"] = "What was deleted can come back",
        ["Tour.2.Body"] = "Folders of removed programs are not erased but moved to a holding area and kept for 30 days. Your own files — large ones and duplicate copies — go to the Recycle Bin, where you restore them the usual way.\n\nRegistry keys are saved to a file before deletion: double-clicking it puts everything back.",
        ["Tour.2.Aside"] = "Temporary files and caches are the exception: those are deleted for good. They are recreated anyway, and keeping copies would free no space at all.",

        ["Tour.3.Title"] = "The numbers are honest",
        ["Tour.3.Body"] = "After the work you see two figures: how much was deleted, and how much actually became free. They often differ — a running program is holding a file, or what was deleted is waiting in the Recycle Bin.\n\nThe difference is explained line by line rather than hidden.",
        ["Tour.3.Aside"] = "If a cleanup achieved nothing, the program says so plainly instead of claiming someone else's gigabytes.",

        ["Tour.4.Title"] = "Where to click",
        ["Tour.4.Body"] = "The sections are on the left. Junk cleanup handles temporary files and is the safest place to begin. Programs removes an application together with the traces its uninstaller left behind. Startup shows what launches with Windows.\n\nDisk space shows where it went, and “Show as a map” shows how the pieces compare. Settings is where automatic cleanup and the clock icon are turned on.",
        ["Tour.4.Aside"] = "Red marks what needs attention. Grey marks what the program will not touch.",

        ["Update.Available"] = "Version {0} is out. Nothing installs by itself: until this program is code-signed, running an update behind your back is not acceptable.",
        ["Update.Open"] = "Open the page",
        ["Update.Later"] = "Not now",
        ["Update.Never"] = "Stop checking",

        ["Uninstall.WindowTitle"] = "Uninstall a program",
        ["Uninstall.ConfirmSubtitle"] = "Check that this is the right program. Once the uninstaller starts, it cannot be stopped.",
        ["Uninstall.Publisher"] = "Publisher:",
        ["Uninstall.Version"] = "Version:",
        ["Uninstall.Location"] = "Directory:",
        ["Uninstall.Scope"] = "Installed:",
        ["Uninstall.NotSpecified"] = "not stated",
        ["Uninstall.VersionUnknown"] = "not stated",
        ["Uninstall.ForAll"] = "for everyone on this computer",
        ["Uninstall.ForYou"] = "just for you",
        ["Uninstall.WarningTitle"] = "Worth knowing before you click",
        ["Uninstall.HowTitle"] = "How this goes",
        ["Uninstall.How1"] = "1. The program's own uninstaller starts. It is not ours: what it asks and what it removes is its decision, not Vacate's.",
        ["Uninstall.How2"] = "2. Then Vacate looks for whatever the uninstaller left behind.",
        ["Uninstall.How3"] = "3. What it finds is shown as a list — removing it is your call. Nothing disappears without your checkmark.",
        ["Uninstall.Start"] = "Uninstall program",
        ["Uninstall.StartForced"] = "Force removal",
        ["Uninstall.RemoveMarked"] = "Remove checked",
        ["Uninstall.LeaveAsIs"] = "Leave as is",
        ["Uninstall.RunningTitle"] = "The uninstaller is running",
        ["Uninstall.RunningSubtitle"] = "Answer its questions in its own window. Vacate waits until it finishes.",
        ["Uninstall.Running"] = "Removing “{0}”…",
        ["Uninstall.SearchingTitle"] = "Looking for traces",
        ["Uninstall.SearchingSubtitle"] = "Checking program directories and registry keys.",
        ["Uninstall.Searching"] = "Searching…",
        ["Uninstall.LeftoversTitle"] = "What the uninstaller left behind",
        ["Uninstall.LeftoversSubtitle"] = "Uncheck anything you are unsure about. Only checked items are removed.",
        ["Uninstall.RemovingTitle"] = "Removing traces",
        ["Uninstall.RemovingSubtitle"] = "Directories move to quarantine; registry keys are deleted.",
        ["Uninstall.RemovingElevated"] = "Some traces sit in system folders, so Windows will now ask for administrator rights.",
        ["Uninstall.Removing"] = "Removing {0} items…",
        ["Uninstall.Done"] = "Done",
        ["Uninstall.NothingRemoved"] = "Nothing removed",
        ["Uninstall.WhatHappened"] = "What happened:",
        ["Uninstall.NoTraces"] = "No files of this program were found.",
        ["Uninstall.FailedTitle"] = "The removal did not finish",
        ["Uninstall.FailedBody"] = "The uninstaller did not complete.",
        ["Uninstall.FailedNote"] = "No trace search was done: the program may still be installed, and its working files could be mistaken for leftovers.",
        ["Uninstall.WorkedOut"] = "The uninstaller finished.",
        ["Uninstall.NothingChecked"] = "Nothing is checked. The program is uninstalled; its traces stay where they are.",
        ["Uninstall.NothingLeft"] = "Nothing left to remove",
        ["Uninstall.VanishedWhileReading"] = "The checked items vanished while you were reading the list.",
        ["Uninstall.WarnRuntime"] = "This looks like a component other programs depend on. Removing it stops those programs from starting — and the connection to this action will not be obvious later.",
        ["Uninstall.WarnNoUninstaller"] = "The program never told Windows how to remove it. Vacate will look for leftover files and take the entry out of the installed list.",
        ["Uninstall.WarnMissingUninstaller"] = "The program's uninstaller is gone: the registration outlived the program. Vacate will look for leftover files and take the entry out of the installed list.",
        ["Uninstall.WarnMachineScope"] = "The program is installed for everyone on this computer, so Windows will ask for administrator rights.",
        ["Uninstall.HintUnchecked"] = "{0} of {1} checked. Items rated “possible” are left unchecked: only part of the name matches, and it may well belong to something else. Read the paths yourself.",
        ["Uninstall.HintAll"] = "All {0} found items are checked. Directories go to quarantine and come back with undo.",
        ["Uninstall.Certain"] = "certainly its own",
        ["Uninstall.Likely"] = "most likely its own",
        ["Uninstall.Possible"] = "possibly someone else's",
        ["Uninstall.Directory"] = "Directory",
        ["Uninstall.RegistryKey"] = "Registry key",
        ["Uninstall.RemovedCount"] = "Items removed: {0}",
        ["Uninstall.FreedOf"] = "Actually freed: {0} of the {1} claimed",
        ["Uninstall.ByElevated"] = "Carried out by a separate process with administrator rights.",
        ["Uninstall.Skipped"] = "Skipped: {0}",
        ["Uninstall.Failed"] = "Could not remove: {0}",
        ["Uninstall.Denied"] = "Refused by safety checks: {0}",
        ["Uninstall.UndoHint"] = "Directories stay in quarantine for 30 days. To bring them back:",
        ["Uninstall.BackupHint"] = "A backup of the deleted registry keys was saved to:",
        ["Uninstall.BackupHowTo"] = "Double-click that file to restore them.",
        ["Uninstall.RightsRefused"] = "The traces stay where they are. The program itself is already uninstalled.",
        ["Uninstall.StillListed"] = "The program stays in the installed list. Try again, or remove the entry through Settings → Apps.",
        ["Apps.NoUninstallCommand"] = "The program never told Windows how to remove it",
        ["Apps.Status"] = "{0} in total, {1} of them runtimes. Sizes are self-reported and often understated.",
        ["Apps.BatchTitle"] = "Removing several programs",
        ["Apps.BatchBody"] = "{0} programs selected.\n\n{1}\n\nThey are removed one after another: each gets its own window, and each uninstaller asks its own questions.\n\nYou can stop at any point — what you cancel stays put.\n\nContinue?",
        ["Startup.CannotToggle"] = "This entry cannot be switched: without it the system may stop working.",
        ["Startup.TurnOn"] = "turn on",
        ["Startup.TurnOff"] = "turn off",
        ["Startup.ConfirmTitle"] = "Startup: {0}",
        ["Startup.WillBeOn"] = "“{0}” will start with Windows.\n\n",
        ["Startup.WillBeOff"] = "“{0}” will no longer start with Windows.\n\n",
        ["Startup.ServiceNote"] = "The service switches to manual start: it will not launch on its own, but a program that needs it can still start it.\n\n",
        ["Startup.ShortcutNote"] = "The shortcut is renamed, not deleted — the same action brings it back.\n\n",
        ["Startup.RegistryNote"] = "The entry is marked rather than deleted — the same way Task Manager does it. It can be brought back at any time.\n\n",
        ["Startup.ElevationNote"] = "The entry is shared by everyone on this computer, so Windows will ask for administrator rights.\n\n",
        ["Startup.NoExecutor"] = "Could not start the helper process.",
        ["Startup.ToggleFailed"] = "The entry could not be switched. For details run: vacate-cli startup",
        ["Startup.RightsRefused"] = "You declined to grant administrator rights.",
        ["Startup.Status"] = "{0} programs, {1} services.",
        ["Startup.SourceRegistry"] = "registry",
        ["Startup.SourceFolder"] = "startup folder",
        ["Startup.SourceTask"] = "scheduled task",
        ["Startup.SourceService"] = "service",
        ["Extensions.StatusDangerous"] = "{0} in total. With access to every site: {1} — such an extension sees everything you open.",
        ["Extensions.StatusSafe"] = "{0} in total. None of them can read every site.",
        ["Disk.DeleteTitle"] = "Deleting files",
        ["Disk.NotAFile"] = "This row is a summary by file type, not a single file.\n\nSelect a large file or a group of duplicate copies.",
        ["Disk.ListStale"] = "Those files are gone — the list is stale. Refresh it.",
        ["Disk.OneFile"] = "File “{0}” ({1})",
        ["Disk.ExtraCopies"] = "Extra copies: {0}, freeing {1}",
        ["Disk.WillKeep"] = "Will be kept: {0}\n\n",
        ["Disk.CloudWarning"] = "WARNING: this file is in a synced folder. It disappears from every device you own, including your phone, and the Recycle Bin only restores it here.\n\n",
        ["Disk.ToRecycleBin"] = "Everything deleted goes to the Recycle Bin.\n\nContinue?",
        ["Disk.DeleteResult"] = "Deleted: {0}. Freed: {1}.\n\nThe space returns fully once the Recycle Bin is emptied.",
        ["Disk.FileKind"] = "file type",
        ["Disk.FilesCount"] = "{0} files",
        ["Disk.CloudNote"] = "Deleting this reaches every device you own",
        ["Disk.CopiesCount"] = "{0} identical copies",
        ["Disk.CopiesNote"] = "That is what you free by keeping one copy",
        ["Disk.CopiesCloudNote"] = "That is what you free by keeping one copy. Deleting this reaches every device you own",
        ["Disk.Status"] = "Scanned {0} files, {1}.",
        ["Disk.StatusDuplicates"] = " Duplicates could free {0}.",
        ["Disk.StatusSkipped"] = " Left out of the count: {0}.",
        ["Integrity.Title"] = "Integrity check",
        ["Integrity.Confirm"] = "Windows will check its own system files and repair damaged ones.\n\nThis takes 10 to 40 minutes. The check cannot be stopped: closing its window does not interrupt it.\n\nA window with its progress will open, and Windows will ask for administrator rights.\n\nStart?",
        ["Integrity.NoCli"] = "vacate-cli.exe, which runs the check, is missing next to the program.\n\nThe installation looks incomplete — reinstall it.",
        ["Integrity.NoResult"] = "The check finished, but its result could not be read.",
        ["Integrity.NoReport"] = "The check finished, but its result never reached the program.",
        ["Health.Temperature"] = "temperature {0} °C",
        ["Health.Wear"] = "wear {0}%",
        ["Health.PowerOn"] = "{0} h powered on",
        ["Health.NotReported"] = "The drive does not report: {0}",
        ["Health.NeedsAttention"] = "needs attention",
        ["Health.Healthy"] = "healthy",
        ["Health.Warning"] = "warnings",
        ["Health.Unhealthy"] = "failing",
        ["Health.Unknown"] = "not reported",
        ["Health.NoDisks"] = "Drive information is unavailable. Some of it requires administrator rights.",
        ["Health.DiskCount"] = "Drives: {0}.",
        ["Clean.Found"] = "Found {0} items, {1}. This is an upper bound: some files may be in use.",
        ["Clean.CatBrowsers"] = "Sites will load noticeably slower the first time. Passwords and tabs are untouched.",
        ["Clean.CatLogs"] = "System event logs. Only useful when investigating a problem.",
        ["Clean.CatCrash"] = "Reports about crashes that already happened.",
        ["Clean.CatDelivery"] = "Downloaded Windows updates. They are fetched again if needed.",
        ["Clean.NeedsRightsNote"] = "The program window runs without administrator rights and cannot look in here. Check it, and Windows will ask for rights when cleaning while a separate process does the work.",
        ["Clean.AndMore"] = "{0}  and {1} more",
        ["Clean.ConfirmTitle"] = "Cleanup",
        ["Clean.NothingCheckedBody"] = "No categories are checked. Check at least one, or there is nothing to delete.",
        ["Clean.ConfirmBody"] = "{0} items will be deleted, about {1}.\n\nThese are temporary files and caches: they are recreated, but cannot be restored.",
        ["Clean.ConfirmElevatedOnly"] = "The checked categories cannot be read by the program window.\n\nA separate process with administrator rights will scan and clean them.",
        ["Clean.WhatWillGo"] = "\n\nWhat will be cleaned:\n",
        ["Clean.ElevationNote"] = "\n\nSome files sit in system folders, so Windows will ask for administrator rights. The program window itself never gets them: a separate process does the work.",
        ["Clean.WouldProcess"] = "Would have processed: {0} items, {1}.",
        ["Clean.NothingChangedOnDisk"] = "Nothing on disk changed.",
        ["Clean.Deleted"] = "Deleted: {0} items, {1} claimed.",
        ["Clean.ByElevated"] = " Carried out by a process with administrator rights.",
        ["Clean.ActuallyFreed"] = "Actually freed: {0}",
        ["Clean.WhyHeld"] = "held by a running program; returns when it closes",
        ["Clean.WhyNotDeleted"] = "could not be deleted",
        ["Clean.WhyHardLinked"] = "the file is listed twice but occupies space once",
        ["Clean.WhyCompressed"] = "compressed files took less room on disk",
        ["Clean.WhyQuarantine"] = "in quarantine; frees up once it expires",
        ["Clean.WhyRecycleBin"] = "in the Recycle Bin; frees up once it is emptied",
        ["Clean.Cat.TempUser"] = "Your temporary files",
        ["Clean.Cat.TempSystem"] = "System temporary files",
        ["Clean.Cat.Logs"] = "Windows logs",
        ["Clean.Cat.Browsers"] = "Browser caches",
        ["Clean.Cat.Crash"] = "Program crash reports",
        ["Clean.Cat.Delivery"] = "Downloaded Windows updates",
        ["Clean.Cat.Other"] = "Other",
        ["Dashboard.Title"] = "Overview",
        ["Dashboard.Subtitle"] = "What is going on with this computer right now.",
        ["Dashboard.Scan"] = "See what turns up",
        ["Map.Title"] = "Disk map",
        ["Map.Subtitle"] = "The area of each tile is the space it takes. Click to open a folder; click “files in this folder” to reveal it in Explorer.",
        ["Map.Up"] = "Up",
        ["Map.Counting"] = "Measuring…",
        ["Map.Empty"] = "This is empty, or its contents are unreadable.",
        ["Map.Total"] = "{0} across {1} items.",
        ["Map.Unreadable"] = " Unreadable: {0} — their space is not counted.",
        ["Map.TooSmall"] = " Too small to draw on the map: {0}.",
        ["Map.LooseFiles"] = "files in this folder",
        ["Hunter.Title"] = "What program is this",
        ["Hunter.Subtitle"] = "Press the crosshair, drag it onto the window you mean without letting go, and release. Vacate works out what started it.",
        ["Hunter.Uninstall"] = "Uninstall this program",
        ["Hunter.PointAt"] = "Point the crosshair at a window",
        ["Hunter.Dragging"] = "Drag the crosshair to the window…",
        ["Hunter.NotIdentified"] = "Program not identified",
        ["Hunter.WindowTitle"] = "Window title: {0}",
        ["Hunter.StartedFrom"] = "Started from:  {0}",
        ["Crash.Title"] = "Vacate",
        ["Crash.Body"] = "Something went wrong that the program could not handle.\n\nWhat happened: {0}\n",
        ["Crash.Saved"] = "Details were saved to:\n{0}\n\nYou can attach it to a bug report — personal data has been stripped from it.",
        ["Tray.Open"] = "Open Vacate",
        ["Tray.QuickClean"] = "Quick cleanup",
        ["Tray.Exit"] = "Exit",
        ["Tray.Tooltip"] = "Vacate — cleanup and maintenance",
        ["Tray.Started"] = "Cleanup started in the background.",
        ["Tray.NoCli"] = "vacate-cli.exe is missing next to the program — the installation is incomplete.",
        ["Elevated.NoReport"] = "The work was done, but the elevated process never reported back",
        ["Common.Items"] = "items",
        ["Window.Minimize"] = "Minimise",
        ["Window.Maximize"] = "Maximise",
        ["Dashboard.Space"] = "Free on the system drive",
        ["Dashboard.Subtitle2"] = "The state of this computer and what you can do about it now.",
        ["Dashboard.FreeSpace"] = "FREE ON THE SYSTEM DRIVE",
        ["Dashboard.CanFree"] = "CAN BE FREED",
        ["Dashboard.StartupCount"] = "PROGRAMS AT STARTUP",
        ["Dashboard.WhereToStart"] = "Where to start",
        ["Dashboard.QuickNote"] = "A quick cleanup removes only what is recreated anyway: temporary files and caches. It never touches the registry or installed programs.",
        ["Dashboard.LastCleanup"] = "Last cleanup",
        ["Dashboard.NoCleanups"] = "No cleanups yet.",
        ["Dashboard.DiskFull"] = "The drive is {0}% full",
        ["Dashboard.DiskFullNote"] = "With little free space left, Windows becomes noticeably slower.",
        ["Dashboard.DiskAttention"] = "Drive {0}: its readings need attention",
        ["Dashboard.DiskAttentionNote"] = "Back up anything important.",
        ["Dashboard.ManyStartup"] = "{0} programs start with Windows",
        ["Dashboard.ManyStartupNote"] = "Each one adds seconds to how long signing in takes.",
        ["Dashboard.LastSession"] = "{0} — {1} items processed, {2} claimed, {3} actually freed.",
        ["Dashboard.Searching"] = "Searching…",
        ["Dashboard.FoundJunk"] = "Found {0} items. See Junk cleanup for details.",
    };

    private static bool _english;

    /// <summary>Английский язык выбран.</summary>
    public static bool IsEnglish => _english;

    /// <summary>
    /// Выбрать язык.
    /// </summary>
    /// <param name="language">
    /// «ru», «en» или пустое значение — тогда язык берётся из настроек системы.
    /// </param>
    public static void Use(string? language)
    {
        _english = language?.ToLowerInvariant() switch
        {
            "en" => true,
            "ru" => false,

            // Русский для русской системы, английский для любой другой:
            // угадывать по одному языку из сотни бессмысленно, а два
            // покрывают ровно то, что переведено.
            _ => !CultureInfo.CurrentUICulture.TwoLetterISOLanguageName.Equals("ru", StringComparison.OrdinalIgnoreCase),
        };
    }

    /// <summary>Текст по ключу.</summary>
    public static string Get(string key)
    {
        if (_english && English.TryGetValue(key, out var english))
        {
            return english;
        }

        // Ключ вместо фразы — это внутренности программы на виду у человека.
        // Русский текст здесь честнее.
        return Russian.TryGetValue(key, out var russian) ? russian : key;
    }

    /// <summary>Ключи, для которых нет английского перевода. Нужно проверке полноты.</summary>
    internal static IEnumerable<string> MissingEnglishKeys() => Russian.Keys.Where(k => !English.ContainsKey(k));
}
